---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: https://stg-api.stackbit.com/project/60c06ef769f4ac001679a134/webhook/forestry
sections:
- type: document
  path: _data/config.json
  label: Site Configuration
  templates:
  - config
- type: directory
  path: _data/team
  label: Person
  create: all
  match: "**/*"
  new_doc_ext: yaml
  templates:
  - person
- type: directory
  path: _data/categories
  label: Category
  create: all
  match: "**/*"
  new_doc_ext: yaml
  templates:
  - category
- type: jekyll-pages
  label: Pages
  create: all
  new_doc_ext: md
  templates:
  - page
  - post
  - advanced
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
